[package]
name = "bevy_mod_picking"
version = "0.3.8-alpha.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A 3D mouse picking and raycasting plugin for Bevy."
repository = "https://github.com/aevyrie/bevy_mod_picking/"
keywords = ["gamedev", "graphics", "picking", "bevy", "3d", "raycast"]
categories = ["game-engines", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.4", default-features = false, features = ["render"] }
bevy_fly_camera = "0.6"
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "master", default-features = false, features = ["render"] }

[features]
example_deps = [ "bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/bevy_gltf", "bevy/x11" ]

[[example]]
name = "3d_scene"
required-features = [ "example_deps" ]

[[example]]
name = "events"
required-features = [ "example_deps" ]

[[example]]
name = "multiple_windows"
required-features = [ "example_deps" ]

[[example]]
name = "stress_test"
required-features = [ "example_deps" ]
